name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean && Install dependencies
        run: flutter clean && flutter pub get

      - name: Build website
        # this is for github pages
#         run: flutter build web --web-renderer html --base-href="/Termux/" 
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
